"""Manual trigger for extraction: `python -m docfactory.agents.run_extraction "<DocStore path>" [--entity <Entity> ...] [--force]`.

The path is a stored file, e.g. "ReadmeForge/ReadmeForge SRS v0.3.pdf". Every entity tagged in the file is extracted (or only the
named ones), one small LLM call per batch of its chunks; entities whose chunks did not change since the last run are skipped
unless --force. Settings come from .env like run_ingestion. Facts are saved as drafts, generated by okf-extraction-agent/<model>.
"""
import argparse
import sys

from docfactory import db
from docfactory.agents.entity_extractor import EntityExtractor
from docfactory.agents.model_client_factory import default_client
from docfactory.env_file import load_env_file
from docfactory.extract.extraction_pipeline import extract_file, format_reports


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="python -m docfactory.agents.run_extraction")
    parser.add_argument("path", help="a stored file, as DocStore/<scope>/<name> without the DocStore/ prefix")
    parser.add_argument("--entity", action="append", help="extract only this entity (repeatable), e.g. FunctionalRequirements")
    parser.add_argument("--force", action="store_true", help="re-extract entities whose chunks are unchanged")
    args = parser.parse_args(argv)
    path = args.path.replace("\\", "/").strip("/")
    if db.get_docstore_row(path) is None:
        print(f"{path!r} is not in the DocStore; stored files:")
        for row in db.list_docstore_rows():
            print(f"  {row['FullPath']}")
        return 1
    load_env_file()  # settings from .env; variables already set in the shell win
    try:
        reports = extract_file(path, EntityExtractor(default_client()), args.entity, args.force)
    except ValueError as error:
        print(error)
        return 2
    print(format_reports(path, reports))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
