"""Manual trigger for the extraction agent: `python -m docfactory.agents.run_extraction "<DocStore path>"`.

The path is a stored file as `list_docstore` shows it, e.g. "ReadmeForge/ReadmeForge SRS v0.3.pdf". Settings come from .env like
run_ingestion (a larger DOCFACTORY_NUM_CTX is needed on Ollama). Facts are saved as drafts, generated by okf-extraction-agent/<model>.
"""
import sys

from docfactory import db
from docfactory.agents.extraction_agent import ExtractionAgent
from docfactory.agents.model_client_factory import default_client
from docfactory.env_file import load_env_file


def main(argv: list[str]) -> int:
    if len(argv) != 1:
        print('usage: python -m docfactory.agents.run_extraction "<DocStore path>"')
        return 2
    path = argv[0].replace("\\", "/").strip("/")
    if db.get_docstore_row(path) is None:
        print(f"{path!r} is not in the DocStore; stored files:")
        for row in db.list_docstore_rows():
            print(f"  {row['FullPath']}")
        return 1
    load_env_file()  # settings from .env; variables already set in the shell win
    print(ExtractionAgent(default_client()).run(path))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
