"""Renders docs/ontology.md, the generated view of the ingestion ontology: `python -m docfactory.ontology.ontology_render`.

Entities, their meaning and their embedded facts come from the entity models (the single source of truth); the tagging signals come
from signals.json. Same inputs, same bytes. Never edit the .md by hand: change the models or signals.json and regenerate.
"""
import re
import sys
from typing import get_args

from docfactory.db import PROJECT_ROOT
from docfactory.models.doc_factory_model import DocFactoryModel
from docfactory.ontology.signals import load_signals
from docfactory.saver_resolution import entity_saver_classes

OUTPUT = PROJECT_ROOT / "docs" / "ontology.md"


def _first_sentence(text: str | None) -> str:
    """Up to the first full stop that ends a sentence ('e.g.' and 'i.e.' do not), so the example stays with its description."""
    text = " ".join((text or "").split())
    match = re.search(r"(?<!e\.g)(?<!i\.e)\.\s", text)
    return text if match is None else text[: match.start() + 1]


def _item_model(annotation) -> type[DocFactoryModel] | None:
    """The model of a list-of-models (or nested model) field, None for plain fields."""
    if isinstance(annotation, type) and issubclass(annotation, DocFactoryModel):
        return annotation
    for argument in get_args(annotation):
        found = _item_model(argument)
        if found is not None:
            return found
    return None


def _fact_lines(model: type[DocFactoryModel]) -> list[str]:
    lines = []
    for name, field in model.model_fields.items():
        lines.append(f"- `{name}`: {_first_sentence(field.description)}")
        item = _item_model(field.annotation)
        if item is not None:
            lines += [f"  - `{sub}`: {_first_sentence(f.description)}" for sub, f in item.model_fields.items()]
    return lines


def _signal_line(label: str, values: list[str]) -> str:
    return f"- {label}: " + (", ".join(f"`{v}`" for v in values) if values else "_none_")


def render_ontology() -> str:
    """The full ontology document."""
    signals = {entry.entity: entry for entry in load_signals()}
    out = [
        "# Ontology",
        "",
        "Generated by `python -m docfactory.ontology.ontology_render`; do not edit. Entities and facts come from the entity models,",
        "tagging signals from `docfactory/ontology/signals.json`.",
        "",
        "Ingestion splits each original into chunks and tags every chunk with the entities it informs: a **heading term** in the chunk's",
        "heading trail (inherited by sub-sections) or an **identifier pattern** in its text is strong evidence; **keywords** are weak",
        "evidence. Chunks the signals cannot tag go to the LLM fallback.",
        "",
    ]
    for saver_class in entity_saver_classes():
        model = saver_class.model
        entry = signals[model.__name__]
        keys = ", ".join(f"`{pattern}`" for pattern in saver_class.key_patterns)
        out += [
            f"## {model.__name__}",
            "",
            _first_sentence(model.__doc__),
            "",
            f"Keys: {keys}",
            "",
            "**Facts**",
            "",
            *_fact_lines(model),
            "",
            "**Tagging signals**",
            "",
            _signal_line("Heading terms", entry.heading_terms),
            _signal_line("Identifier patterns", entry.id_patterns),
            _signal_line("Keywords", entry.keywords),
            "",
        ]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render_ontology(), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
